apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  CLUSTER_ID: "7PWQxmoYTjioW4QMpFozXA"
  # 统一的集群 ID
  KAFKA_CLUSTER_ID: "7PWQxmoYTjioW4QMpFozXA" 
  
  # 节点 ID
  KAFKA_NODE_ID: "1" 

  # 启用 KRaft 模式，角色为 Broker 和 Controller
  KAFKA_PROCESS_ROLES: "broker,controller"  # 移除 CFG_ 前缀，直接使用 KAFKA_
  
  # KRaft 选举 Quorum (使用 Pod FQDN 确保地址稳定)
  # 格式: <node_id>@<pod_name>.<headless_service_name>.<namespace>.svc.cluster.local:<controller_port>
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-kraft-0.kafka-headless.kafka.svc.cluster.local:9093"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  
  # 定义监听器
  KAFKA_LISTENERS: "PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"

  # 广播监听器 (外部需要手动替换为 Node IP 和 NodePort)
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-kraft-0.kafka-headless.kafka.svc.cluster.local:9092,EXTERNAL://172.31.17.97:33094"
  
  # 日志存储路径
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  
  # 最小化配置
  KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_NUM_PARTITIONS: "1"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_HEAP_OPTS: "-Xmx768M -Xms768M"
---
# 2. Kubernetes Service (Headless) 供 StatefulSet 内部使用
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
spec:
  type: ClusterIP
  clusterIP: None # Headless Service
  selector:
    app: kafka
  ports:
  - name: plaintext
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093

---
# 3. Kubernetes StatefulSet：运行 Kafka Pod
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-kraft
  namespace: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0
        # 资源限制为最低配置
        resources:
          requests:
            memory: "768Mi" # 增加一点内存以确保稳定启动
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 9092
          name: plaintext
        - containerPort: 9094
          name: external
        - containerPort: 9093
          name: controller
        envFrom:
        - configMapRef:
            name: kafka-config
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

---
# 4. Kubernetes Service (NodePort) 暴露给外部访问
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
  - name: external-listener
    port: 9094
    targetPort: 9094
    nodePort: 30094 # 预留 NodePort，可以在 30000-32767 范围内选择